/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vepSol from "./VEP.sol";
export type { vepSol };
export type { CASP } from "./CASP";
export * as factories from "./factories";
export { CASP__factory } from "./factories/CASP__factory";
export type { VEP } from "./VEP.sol/VEP";
export { VEP__factory } from "./factories/VEP.sol/VEP__factory";
